{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier-Oblique;}
{\colortbl;\red255\green255\blue255;\red34\green79\blue188;}
{\*\expandedcolortbl;;\csgenericrgb\c13206\c30848\c73913;}
\margl1440\margr1440\vieww22420\viewh13980\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\i\fs38 \cf1 \cb2 \CocoaLigature0 ---\
- hosts: target\
  become: yes\
  remote_user: ec2-user\
  become_user: root\
  tasks:\
  - name: Download Long Term Jenkins release\
    get_url:\
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo\
      dest: /etc/yum.repos.d/jenkins.repo\
\
  - name: Import jenkins key from url\
    ansible.builtin.rpm_key:\
      state: present\
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key\
\
  - name: yum update\
    yum:\
      name: '*'\
      state: latest\
\
  - name: Install java\
    yum:\
      name: java-11-openjdk-devel\
      state: present\
\
  - name: Install jenkins\
    yum:\
      name: jenkins\
      state: latest\
\
  - name: daemon-reload to pick up config changes\
    ansible.builtin.systemd:\
      daemon_reload: yes\
\
  - name: Start jenkins\
    ansible.builtin.systemd:\
      name: jenkins\
      state: started\
}